dist: xenial
language: python
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
stages:
  - lint
  - examples
  - tests
jobs:
  include:
    - stage: lint
      env:
        - TOXENV=check
    - stage: lint
      env:
        - TOXENV=docs
    - stage: tests
      python: '2.7'
      env:
        - TOXENV=py27-t310-c45
    - stage: tests
      python: '2.7'
      env:
        - TOXENV=py27-t40-c45
    - stage: tests
      python: '2.7'
      env:
        - TOXENV=py27-t41-c45
    - stage: tests
      python: '3.4'
      env:
        - TOXENV=py34-t310-c45
    - stage: tests
      python: '3.4'
      env:
        - TOXENV=py34-t40-c45
    - stage: tests
      python: '3.4'
      env:
        - TOXENV=py34-t41-c45
    - stage: tests
      python: '3.5'
      env:
        - TOXENV=py35-t310-c45
    - stage: tests
      python: '3.5'
      env:
        - TOXENV=py35-t40-c45
    - stage: tests
      python: '3.5'
      env:
        - TOXENV=py35-t41-c45
    - stage: tests
      python: '3.6'
      env:
        - TOXENV=py36-t310-c45
    - stage: tests
      python: '3.6'
      env:
        - TOXENV=py36-t40-c45
    - stage: tests
      python: '3.6'
      env:
        - TOXENV=py36-t41-c45
    - stage: tests
      python: '3.7'
      env:
        - TOXENV=py37-t310-c45
    - stage: tests
      python: '3.7'
      env:
        - TOXENV=py37-t40-c45
    - stage: tests
      python: '3.7'
      env:
        - TOXENV=py37-t41-c45
    - stage: tests
      python: 'pypy2.7-6.0'
      env:
        - TOXENV=pypy-t310-c45
    - stage: tests
      python: 'pypy2.7-6.0'
      env:
        - TOXENV=pypy-t40-c45
    - stage: tests
      python: 'pypy2.7-6.0'
      env:
        - TOXENV=pypy-t41-c45
    - stage: tests
      python: 'pypy3.5-6.0'
      env:
        - TOXENV=pypy3-t310-c45
    - stage: tests
      python: 'pypy3.5-6.0'
      env:
        - TOXENV=pypy3-t40-c45
    - stage: tests
      python: 'pypy3.5-6.0'
      env:
        - TOXENV=pypy3-t41-c45
    - stage: examples
      python: '3.6'
      script: cd $TARGET; tox -v
      env:
          - TARGET=examples/src-layout
    - stage: examples
      python: '3.6'
      script: cd $TARGET; tox -v
      env:
          - TARGET=examples/adhoc-layout
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
